In [1]:
%load_ext autoreload
%autoreload 2

In [40]:
from config import DATA_DIR
from src.etl import load_protein_data, normalize_protein_data
from config import PROTEIN_METADATA, PROTEIN_SELECTED
import pandas as pd
import numpy as np

In [52]:
df = load_protein_data()[PROTEIN_METADATA + PROTEIN_SELECTED]

In [55]:
normalize_protein_data(df)

,patient_id,sample_id,tumor_type,ajcc_stage,cancerseek_score,cancerseek_result,ca_125,cea,ca19_9,prolactin,hgf,opn,myeloperoxidase,timp_1
0,CRC 455,CRC 455 PLS 1,Colorectum,I,0.938342,Positive,0.00,0.00,0.00,0.00,377.26,0.00,0.00,0.00
1,CRC 456,CRC 456 PLS 1,Colorectum,I,0.925363,Positive,0.00,5902.43,40.91,0.00,659.68,0.00,0.00,0.00
2,CRC 457,CRC 457 PLS 1,Colorectum,II,0.852367,Negative,0.00,0.00,0.00,38375.00,329.07,88896.24,0.00,0.00
3,CRC 458,CRC 458 PLS 1,Colorectum,II,0.617639,Negative,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,CRC 459,CRC 459 PLS 1,Colorectum,II,0.318434,Negative,0.00,0.00,0.00,0.00,370.88,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1812,PAPA 1353,PAPA 1353 PLS 1,Ovary,I,0.980312,Positive,24.82,0.00,42.39,58266.97,0.00,0.00,0.00,167799.61
1813,PAPA 1354,PAPA 1354 PLS 1,Ovary,I,0.999995,Positive,0.00,0.00,0.00,187828.79,374.03,0.00,39.62,123443.76
1814,PAPA 1355,PAPA 1355 PLS 1,Ovary,III,1.000000,Positive,30.48,0.00,0.00,241440.02,0.00,93601.15,0.00,104070.89
1815,PAPA 1356,PAPA 1356 PLS 1,Ovary,II,1.000000,Positive,1469.45,0.00,62.26,140145.70,1153.70,145116.62,64.83,110579.24
1816,PAPA 1357,PAPA 1357 PLS 1,Ovary,III,1.000000,Positive,1428.31,0.00,37.90,111737.24,0.00,103657.44,0.00,0.00